spring:
  servlet:
    multipart:
      max-file-size: '100MB'
      max-request-size: '100MB'

app:
  cors:
    origins:
      - 'https://attacktive.github.io'
      - 'http://localhost:3000'

logging:
  file:
    name: '${user.home}/logs/troubleshooter-editor.log'
