spring:
  servlet:
    multipart:
      max-file-size: '100MB'
      max-request-size: '100MB'

app:
  cors:
    origins: ["*"]

logging:
  file:
    name: '${user.home}/logs/troubleshooter-editor.log'
