name: 'Deploy to the Cloud'
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Set up JDK 21'
        uses: 'actions/setup-java@v4'
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: 'Setup Gradle'
        uses: 'gradle/actions/setup-gradle@v4'
      - name: 'Build with Gradle'
        run: './gradlew clean bootJar'
      - name: 'Change working directory'
        run: 'cd build/libs'
      - id: 'getArchiveFileName'
        name: 'Get archive file name'
        run: 'echo "FILE_NAME=$(printf %s $(ls))" >> $GITHUB_OUTPUT'
      - name: 'Copy to the cloud'
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H 211.188.52.216 > ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp $SOURCE $DESTINATION
        env:
          SOURCE: "build/libs/${{ steps.getArchiveFileName.outputs.FILE_NAME }}"
          DESTINATION: "${{ secrets.SSH_USERNAME }}@211.188.52.216:/home/${{ secrets.SSH_USERNAME }}/troubleshooter-editor-back-end"
