# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: 'Java CI with Gradle'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: 'read'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v5'
      - name: 'Set up JDK 21'
        uses: 'actions/setup-java@v5'
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: 'Setup Gradle'
        uses: 'gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a'
      - name: 'Build with Gradle'
        run: './gradlew compileKotlin compileTestKotlin'
      - name: 'Run tests with Gradle'
        run: './gradlew test jacocoTestReport'
      - name: 'Add coverage report to job summary'
        run: |
          echo "### Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat build/reports/jacoco/test/html/index.html | grep -A 5 "Total.*[0-9]\+" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
