name: 'Push to Docker Hub'
on:
  push:
    tags:
      - '**'
jobs:
  build:
    name: 'Build JAR'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'
      - name: 'Set up JDK 21'
        uses: 'actions/setup-java@v4'
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: 'Build JAR'
        run: './gradlew clean bootJar -x test'
      - name: 'Upload JAR artifact'
        uses: 'actions/upload-artifact@v4'
        with:
          path: |
            build/libs/*.jar
            Dockerfile
  push-to-docker-hub:
    name: 'Push to Docker Hub'
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - name: 'Download JAR artifact'
        uses: 'actions/download-artifact@v4'
      - name: 'Display structure of downloaded files'
        run: ls -R
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'
      - name: 'Log in to Docker Hub'
        uses: 'docker/login-action@v3'
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
      - name: 'Build and push Docker image'
        uses: 'docker/build-push-action@v6'
        with:
          push: true
          file: 'Dockerfile'
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/troubleshooter-editor-back-end:${{ github.ref_name }}"
      - name: 'Logout of Docker Hub'
        run: 'docker logout'
