name: 'Release'
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Create Release'
        uses: 'softprops/action-gh-release@d5382d3e6f2fa7bd53cb749d33091853d4985daf'
        with:
          generate_release_notes: true
